language: objective-c

before_install: 
    -  gem install cocoapods
    -  brew update
    -  brew unlink xctool
    -  brew install xctool --HEAD

script:
    - xcodebuild -workspace Maris.xcworkspace -scheme Maris -sdk iphonesimulator test | xcpretty -c;
